#!/usr/bin/env bash

ECR_PATH=ghcr.io/pirasanthan-jesugeevegan
AMT_RUNNER_DOCKER_IMAGE=${ECR_PATH}/coincover-amt
AMT_RUNNER_DOCKER_IMAGE_CACHE=${AMT_RUNNER_DOCKER_IMAGE}:latest
AMT_RUNNER_DOCKER_IMAGE_REV=${AMT_RUNNER_DOCKER_IMAGE}:${GITHUB_SHA}