name: Docker Build & Push
on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check file changes
        uses: tj-actions/changed-files@v37
        id: verify-changed-files
        with:
          files: |
            Dockerfile.base

      - name: Build Docker base image
        if: steps.verify-changed-files.outputs.any_changed == 'true'
        run: |
          docker build \
          -t ghcr.io/${{github.repository}}:base \
          -f Dockerfile.base .
          docker push -q ghcr.io/${{github.repository}}:base

      - name: Build and push the tagged docker image to Amazon ECR
        run: |
          chmod +x scripts/build-push.sh
          scripts/build-push.sh
