name: Docker Build & Push
on:
  push:
    branches: ['master']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository}}
  GITHUB_SHA: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the tagged docker image to Amazon ECR
        run: |
          chmod +x scripts/build-push.sh
          scripts/build-push.sh
