name: Docker Build & Push
on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check file changes
        id: file_changes
        run: |
          changed=$(git diff --name-only ${{ github.base_ref }}..${{ github.sha }} | grep Dockerfile.base)
          echo "CHANGED_FILES=$changed" >> $GITHUB_ENV

      - name: Build Docker base image
        if: env.CHANGED_FILES == 'Dockerfile.base'
        run: |
          docker pull -q ghcr.io/${{github.repository}}:base
          docker build \
          --cache-from ghcr.io/${{github.repository}}:base \
          -t ghcr.io/${{github.repository}}:base \
          -f Dockerfile.base .

      - name: Build and push the tagged docker image to Amazon ECR
        run: |
          chmod +x scripts/build-push.sh
          scripts/build-push.sh
