name: Load Testing with k6
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d influxdb grafana

      - name: Run k6
        run: |
          docker-compose run --rm k6 run /scripts/ewoks.js

      - name: Stop Docker Compose
        run: docker-compose down
