name: Load Testing with k6

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - grafana
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:8.5.21
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
    ports:
      - '6565:6565'
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Install k6
        uses: loadimpact/k6-action@v1.3.0

      - name: Run k6
        run: |
          docker-compose run --rm k6 run /scripts/ewoks.js

      - name: Stop Docker Compose
        run: docker-compose down
