name: Load Testing with k6
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run k6
        run: |
          npm run test:pt

      - name: Stop Docker Compose
        run: docker-compose down
