name: Load Testing with k6
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          npm install

      - name: K6 test - examples.js
        uses: grafana/k6-action@v0.2.0
        with:
          filename: dist/example.pt.js
          glags: --out json=test_results.json

      - name: Stop Docker Compose
        run: docker-compose down
