name: Playwright Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:ui
      - name: reploy report to s3
        if: always()
        run: |
          chmod +x ./deploy-report.sh
          ./deploy-report.sh

    # steps:
    #   - uses: actions/checkout@v2

    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: us-east-1

    #   - name: Login to ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1

    #   # - name: Pull image from ECR
    #   #   run: |
    #   #     docker pull ${{ steps.login-ecr.outputs.registry }}/my-ecr-repo:my-tag

    #   - name: Run container on EC2
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${ { secrets.HOST_DNS }}
    #       username: ${ { secrets.USERNAME }}
    #       key: ${ { secrets.EC2_SSH_KEY }}
    #       script: |
    #         chmod +x ./build-push.sh
    #         ./run-load-test.sh
