name: Automation Tests
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        description: 'Trigger option'
        required: true
        options:
          - ui
          - api
          - pt
env:
  TEST_TYPE: ${{ github.event.inputs.test_type }}
  USER_NAME: ${{ github.actor }}
  PLAYWRIGHT_JSON_OUTPUT_NAME: 'results.json'

jobs:
  Run_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR registry
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker image from Amazon ECR
        run: docker pull ${ECR_REGISTRY}/ennismore:latest
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}

      - name: Install dependencies
        run: npm i

      - name: Run Test, Generate Report & Upload to S3
        run: |
          chmod +x scripts/run.sh
          scripts/run.sh

    # steps:
    #   - uses: actions/checkout@v2

    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: us-east-1

    #   - name: Login to ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1

    #   # - name: Pull image from ECR
    #   #   run: |
    #   #     docker pull ${{ steps.login-ecr.outputs.registry }}/my-ecr-repo:my-tag

    #   - name: Run container on EC2
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${ { secrets.HOST_DNS }}
    #       username: ${ { secrets.USERNAME }}
    #       key: ${ { secrets.EC2_SSH_KEY }}
    #       script: |
    #         chmod +x ./build-push.sh
    #         ./run-load-test.sh
